"use client"
import {HangBar} from "@/components/hangBar";
import React from "react";
import {FirebaseAuthProvider} from "@/lib/firebase/authentication";
import {ChakraProvider, extendBaseTheme} from '@chakra-ui/react'


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const theme = extendBaseTheme({})

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <ChakraProvider>
            <FirebaseAuthProvider>
                <HangBar></HangBar>
                {children}
            </FirebaseAuthProvider>
        </ChakraProvider>
        </body>
        </html>
    )
}
