import './globals.css'
import {Inter} from 'next/font/google'
import {HangBar} from "@/components/hangBar";
import React from "react";
import {FirebaseAuthProvider} from "@/lib/firebase/authentication";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <HangBar></HangBar>
        <FirebaseAuthProvider>
            {children}
        </FirebaseAuthProvider>
        </body>
        </html>
    )
}
